Repository airbnb/rheostat, pull requests merged in 2018-07, with the labels that each got.

#169 [quality] add react-with-styles namespacing
  src/DefaultBackground.jsx
  src/DefaultHandle.jsx
  src/DefaultProgressBar.jsx
  src/Slider.jsx
  src/themes/DefaultTheme.js
Labels: semver-major: breaking changes

#170 [bugfix] reintroduce background prop
  src/DefaultBackground.jsx
  src/Slider.jsx
Labels: semver-minor: new stuff

#175 [visual] update disabled color
  src/themes/DefaultTheme.js
Labels: semver-patch: bugfixes

#177 Add back pitStyle cache and remove step prop
  src/Slider.jsx
  src/constants/SliderConstants.js
  test/slider-test.jsx
Labels: semver-major: breaking changes, semver-patch: bugfixes

#174 Turn skipped tests back on by stubbing out getSliderBoundingBox
  test/slider-test.jsx
Labels: semver-patch: bugfixes

#178 Do not trigger change event when programmatically updating the slider values
  src/Slider.jsx
  test/slider-test.jsx
Labels: semver-major: breaking changes

#182 [fix] Move theme registration to src
  .storybook-css/config.js
  .storybook/config.js
  scripts/buildCSS.js
  scripts/utils/registerCSSInterfaceWithDefaultTheme.js
  scripts/utils/registerInterfaceWithDefaultTheme.js
  src/initialize.js
  src/utils/registerCSSInterfaceWithDefaultTheme.js
  src/utils/registerInterfaceWithDefaultTheme.js
Labels: question, semver-minor: new stuff
